Nature Harmony – MISSION 3

Etape 0 : Importer les bibliothèques

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

Etape 1 : Charger les données 

In [2]:
df = pd.read_csv("jours.csv")
df

,Jour,Est_Weekend,Est_Ferie,Temperature,Precipitation,Vacance_Scolaire,Nb_Visiteurs,Type_Activite
0,1,0,0,15,2,0,120,1
1,2,0,0,14,0,0,110,1
2,3,1,0,18,0,0,450,1
3,4,1,0,17,0,0,430,1
4,5,0,0,12,15,0,50,0
5,6,0,0,16,1,0,135,1
6,7,0,0,15,0,0,125,1
7,8,0,0,14,0,0,115,1
8,9,0,0,13,0,0,105,1
9,10,1,0,20,0,0,480,1


In [3]:
donnees = df.values
donnees

array([[  1,   0,   0,  15,   2,   0, 120,   1],
       [  2,   0,   0,  14,   0,   0, 110,   1],
       [  3,   1,   0,  18,   0,   0, 450,   1],
       [  4,   1,   0,  17,   0,   0, 430,   1],
       [  5,   0,   0,  12,  15,   0,  50,   0],
       [  6,   0,   0,  16,   1,   0, 135,   1],
       [  7,   0,   0,  15,   0,   0, 125,   1],
       [  8,   0,   0,  14,   0,   0, 115,   1],
       [  9,   0,   0,  13,   0,   0, 105,   1],
       [ 10,   1,   0,  20,   0,   0, 480,   1],
       [ 11,   1,   0,  19,   0,   0, 460,   1],
       [ 12,   0,   0,  11,  12,   0,  45,   0],
       [ 13,   0,   0,  15,   0,   0, 140,   1],
       [ 14,   0,   0,  16,   2,   0, 145,   1],
       [ 15,   0,   1,  22,   0,   0, 550,   1],
       [ 16,   0,   0,  17,   0,   0, 155,   1],
       [ 17,   0,   0,  18,   0,   0, 160,   1],
       [ 18,   1,   0,  21,   1,   0, 490,   1],
       [ 19,   1,   0,  20,   0,   0, 475,   1],
       [ 20,   0,   0,  10,  20,   0,  30,   0],
       [ 21,   0,   

    Etape 2 : Séparer les features (X) et la cible (y)

Colonne 0 → Jour               pas besoin
Colonne 1 → Est_Weekend        feature
Colonne 2 → Est_Ferie          feature
Colonne 3 → Temperature        feature
Colonne 4 → Precipitation      feature
Colonne 5 → Vacance_Scolaire   feature
Colonne 6 → Nb_Visiteurs       (cible Mission 2)
Colonne 7 → Type_Activite      cible Mission 3

In [4]:
X_train = donnees[:, [1, 2, 3, 4, 5]]
X_train

array([[ 0,  0, 15,  2,  0],
       [ 0,  0, 14,  0,  0],
       [ 1,  0, 18,  0,  0],
       [ 1,  0, 17,  0,  0],
       [ 0,  0, 12, 15,  0],
       [ 0,  0, 16,  1,  0],
       [ 0,  0, 15,  0,  0],
       [ 0,  0, 14,  0,  0],
       [ 0,  0, 13,  0,  0],
       [ 1,  0, 20,  0,  0],
       [ 1,  0, 19,  0,  0],
       [ 0,  0, 11, 12,  0],
       [ 0,  0, 15,  0,  0],
       [ 0,  0, 16,  2,  0],
       [ 0,  1, 22,  0,  0],
       [ 0,  0, 17,  0,  0],
       [ 0,  0, 18,  0,  0],
       [ 1,  0, 21,  1,  0],
       [ 1,  0, 20,  0,  0],
       [ 0,  0, 10, 20,  0],
       [ 0,  0, 19,  0,  1],
       [ 0,  0, 20,  0,  1],
       [ 0,  0, 21,  0,  1],
       [ 0,  0, 22,  0,  1],
       [ 0,  0, 23,  0,  1],
       [ 1,  0, 25,  0,  1],
       [ 1,  0, 24,  0,  1],
       [ 0,  0, 12, 18,  1],
       [ 0,  0, 20,  0,  1],
       [ 0,  0, 21,  1,  1],
       [ 0,  0, 18,  0,  0],
       [ 0,  0, 17,  0,  0],
       [ 1,  0, 22,  0,  0],
       [ 1,  0, 21,  0,  0],
       [ 0,  0

In [5]:
y_train = donnees[:, 7]
y_train

array([1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 1])

Etape 3 : Split 70% Train / 30% Test

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, test_size=0.3)

In [7]:
print("Taille X_train :", X_train.shape)
print("Taille X_test  :", X_test.shape)

Taille X_train : (35, 5)
Taille X_test  : (15, 5)


Etape 4 : Entraîner le modèle

In [8]:
modele = LogisticRegression()
modele.fit(X_train, y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [9]:
print("Modèle entraîné !")
print(f"\nCoefficients   : {modele.coef_}")
print(f"Ordonnée orig. : {modele.intercept_[0]:.1f}")

Modèle entraîné !

Coefficients   : [[-0.06052721  0.          0.31812896 -0.7456805   0.00098174]]
Ordonnée orig. : 1.0


Etape 5 : Prédire 

In [10]:
y_pred = modele.predict(X_test)

In [11]:
print("y_test :", y_test)
print("y_pred :", y_pred)

y_test : [1 0 1 1 1 1 1 1 1 1 1 1 1 1 0]
y_pred : [1 0 1 1 1 1 1 1 1 1 1 1 1 1 0]


Etape 6 : Accuracy et Matrice de Confusion

In [12]:
acc = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print(f"Accuracy : {acc:.2f} → le modèle prend la bonne décision {acc*100:.0f}% du temps")
print()
print("Matrice de Confusion :")
print(cm)

Accuracy : 1.00 → le modèle prend la bonne décision 100% du temps

Matrice de Confusion :
[[ 2  0]
 [ 0 13]]


In [13]:
import joblib
joblib.dump(modele, "modele_classification.pkl")

['modele_classification.pkl']