Mission 2

Etape 0 : Importer les bibliothèques

In [2]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split

Etape 1 : Charger les données

In [3]:
df = pd.read_csv("jours.csv")
df

,Jour,Est_Weekend,Est_Ferie,Temperature,Precipitation,Vacance_Scolaire,Nb_Visiteurs,Type_Activite
0,1,0,0,15,2,0,120,1
1,2,0,0,14,0,0,110,1
2,3,1,0,18,0,0,450,1
3,4,1,0,17,0,0,430,1
4,5,0,0,12,15,0,50,0
5,6,0,0,16,1,0,135,1
6,7,0,0,15,0,0,125,1
7,8,0,0,14,0,0,115,1
8,9,0,0,13,0,0,105,1
9,10,1,0,20,0,0,480,1


In [4]:
donnees = df.values
donnees

array([[  1,   0,   0,  15,   2,   0, 120,   1],
       [  2,   0,   0,  14,   0,   0, 110,   1],
       [  3,   1,   0,  18,   0,   0, 450,   1],
       [  4,   1,   0,  17,   0,   0, 430,   1],
       [  5,   0,   0,  12,  15,   0,  50,   0],
       [  6,   0,   0,  16,   1,   0, 135,   1],
       [  7,   0,   0,  15,   0,   0, 125,   1],
       [  8,   0,   0,  14,   0,   0, 115,   1],
       [  9,   0,   0,  13,   0,   0, 105,   1],
       [ 10,   1,   0,  20,   0,   0, 480,   1],
       [ 11,   1,   0,  19,   0,   0, 460,   1],
       [ 12,   0,   0,  11,  12,   0,  45,   0],
       [ 13,   0,   0,  15,   0,   0, 140,   1],
       [ 14,   0,   0,  16,   2,   0, 145,   1],
       [ 15,   0,   1,  22,   0,   0, 550,   1],
       [ 16,   0,   0,  17,   0,   0, 155,   1],
       [ 17,   0,   0,  18,   0,   0, 160,   1],
       [ 18,   1,   0,  21,   1,   0, 490,   1],
       [ 19,   1,   0,  20,   0,   0, 475,   1],
       [ 20,   0,   0,  10,  20,   0,  30,   0],
       [ 21,   0,   

Etape 2 : Séparer les features (X) et la cible (y)

Colonne 1 → Est_Weekend        -> feature  
Colonne 2 → Est_Ferie          -> feature
Colonne 3 → Temperature        -> feature
Colonne 4 → Precipitation      -> feature
Colonne 5 → Vacance_Scolaire   -> feature
Colonne 6 → Nb_Visiteurs       -> cible

In [5]:
X = donnees[:, [1, 2, 3, 4, 5]]
X

array([[ 0,  0, 15,  2,  0],
       [ 0,  0, 14,  0,  0],
       [ 1,  0, 18,  0,  0],
       [ 1,  0, 17,  0,  0],
       [ 0,  0, 12, 15,  0],
       [ 0,  0, 16,  1,  0],
       [ 0,  0, 15,  0,  0],
       [ 0,  0, 14,  0,  0],
       [ 0,  0, 13,  0,  0],
       [ 1,  0, 20,  0,  0],
       [ 1,  0, 19,  0,  0],
       [ 0,  0, 11, 12,  0],
       [ 0,  0, 15,  0,  0],
       [ 0,  0, 16,  2,  0],
       [ 0,  1, 22,  0,  0],
       [ 0,  0, 17,  0,  0],
       [ 0,  0, 18,  0,  0],
       [ 1,  0, 21,  1,  0],
       [ 1,  0, 20,  0,  0],
       [ 0,  0, 10, 20,  0],
       [ 0,  0, 19,  0,  1],
       [ 0,  0, 20,  0,  1],
       [ 0,  0, 21,  0,  1],
       [ 0,  0, 22,  0,  1],
       [ 0,  0, 23,  0,  1],
       [ 1,  0, 25,  0,  1],
       [ 1,  0, 24,  0,  1],
       [ 0,  0, 12, 18,  1],
       [ 0,  0, 20,  0,  1],
       [ 0,  0, 21,  1,  1],
       [ 0,  0, 18,  0,  0],
       [ 0,  0, 17,  0,  0],
       [ 1,  0, 22,  0,  0],
       [ 1,  0, 21,  0,  0],
       [ 0,  0

In [6]:
y = donnees[:, 6]
y

array([120, 110, 450, 430,  50, 135, 125, 115, 105, 480, 460,  45, 140,
       145, 550, 155, 160, 490, 475,  30, 300, 310, 320, 330, 340, 750,
       720,  80, 350, 360, 150, 140, 510, 500,  25, 145, 135, 125, 115,
       530, 520,  20, 160, 165, 600, 175, 180,  90, 100, 190])

Etape 3 : Split 70% Train / 30% Test

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [8]:
# Les features utilisées pour apprendre
print("X_train (features pour apprendre) :")
print(X_train)

# Les features utilisées pour tester
print("\nX_test (features pour tester) :")
print(X_test)

# Les vraies réponses pour apprendre
print("\ny_train (nb visiteurs réels pour apprendre) :")
print(y_train)

# Les vraies réponses qu'on va comparer aux prédictions
print("\ny_test (nb visiteurs réels pour tester) :")
print(y_test)

X_train (features pour apprendre) :
[[ 1  0 19  0  0]
 [ 0  0 22  0  1]
 [ 0  0 10 20  0]
 [ 1  0 11 15  0]
 [ 1  0 21  0  0]
 [ 0  0 19  0  1]
 [ 1  0 18  0  0]
 [ 0  0 15  2  0]
 [ 0  0  8 30  0]
 [ 0  1 22  0  0]
 [ 0  0 13  0  0]
 [ 1  0 24  0  1]
 [ 0  0 23  0  1]
 [ 0  0 16  0  0]
 [ 0  0 14  0  0]
 [ 0  0 18  0  0]
 [ 1  0 21  1  0]
 [ 0  0 20  0  0]
 [ 0  0 15  2  0]
 [ 0  0 16  1  0]
 [ 0  0 12 15  0]
 [ 1  0 20  0  0]
 [ 1  0 12 10  0]
 [ 1  0 23  0  0]
 [ 0  0 21  0  1]
 [ 0  0 15  0  0]
 [ 0  0  9 25  0]
 [ 0  0 16  2  0]
 [ 0  0 18  3  0]
 [ 0  0 14  0  0]
 [ 0  0 20  0  1]
 [ 0  0 14  0  0]
 [ 0  0 19  0  0]
 [ 1  0 25  0  1]
 [ 0  0 17  0  0]]

X_test (features pour tester) :
[[ 0  1 25  0  0]
 [ 0  0 12 18  1]
 [ 1  0 20  0  0]
 [ 0  0 21  0  0]
 [ 0  0 20  0  1]
 [ 1  0 17  0  0]
 [ 0  0 17  0  0]
 [ 0  0 13  0  0]
 [ 1  0 22  0  0]
 [ 0  0 17  0  0]
 [ 1  0 24  0  0]
 [ 0  0 21  1  1]
 [ 0  0 11 12  0]
 [ 0  0 15  0  0]
 [ 0  0 18  0  0]]

y_train (nb visiteurs réels 

Etape 4 : Entaîner le modèle

In [9]:
modele = LinearRegression()
modele.fit(X_train, y_train)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [10]:
print("Modèle entraîné !")
print(f"\nCoefficients   : {modele.coef_}")
print(f"Ordonnée orig. : {modele.intercept_:.1f}")

Modèle entraîné !

Coefficients   : [204.7356504  245.33725431  27.84288674   1.5040588   75.41278277]
Ordonnée orig. : -307.9


Etape 5 : Prédire pour X_test

In [11]:
y_pred = modele.predict(X_test)

print("y_test :", y_test)
print("y_pred :", y_pred)

y_test : [600  80 475 190 350 430 140 115 510 155 530 360  45 125 160]
y_pred : [633.52866022 128.71971949 453.71262261 276.81985895 324.38975498
 370.18396239 165.44831199  54.07676503 509.39839609 165.44831199
 565.08416957 353.73670052  16.43969717 109.76253851 193.29119873]


Etape 6 : Évaluer le modèle avec RMSE et R²

In [12]:
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print(f"RMSE : {rmse:.1f} visiteurs  → en moyenne, le modèle se trompe de {rmse:.0f} visiteurs")
print(f"R²   : {r2:.2f}             → le modèle explique {r2*100:.0f}% de la variabilité")

RMSE : 39.7 visiteurs  → en moyenne, le modèle se trompe de 40 visiteurs
R²   : 0.95             → le modèle explique 95% de la variabilité


In [13]:
import joblib
joblib.dump(modele, "modele_regression.pkl")

['modele_regression.pkl']